# Form implementation generated from reading ui file 'stopwatch.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Stopwatch(object):
    def setupUi(self, Stopwatch):
        Stopwatch.setObjectName("Stopwatch")
        Stopwatch.resize(400, 300)
        self.title = TitleLabel(parent=Stopwatch)
        self.title.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Stopwatch)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 60, 211, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSw = PushButton(parent=self.gridLayoutWidget)
        self.buttonSw.setCheckable(True)
        self.buttonSw.setObjectName("buttonSw")
        self.horizontalLayout.addWidget(self.buttonSw)
        self.buttonReset = PushButton(parent=self.gridLayoutWidget)
        self.buttonReset.setCheckable(False)
        self.buttonReset.setFlat(False)
        self.buttonReset.setObjectName("buttonReset")
        self.horizontalLayout.addWidget(self.buttonReset)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.statusShow = BodyLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusShow.setFont(font)
        self.statusShow.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusShow.setObjectName("statusShow")
        self.gridLayout.addWidget(self.statusShow, 0, 0, 1, 1)
        self.buttonShowTime = PushButton(parent=self.gridLayoutWidget)
        self.buttonShowTime.setObjectName("buttonShowTime")
        self.gridLayout.addWidget(self.buttonShowTime, 3, 0, 1, 1)
        self.statusShow.setBuddy(self.statusShow)

        self.retranslateUi(Stopwatch)
        QtCore.QMetaObject.connectSlotsByName(Stopwatch)
        Stopwatch.setTabOrder(self.buttonSw, self.buttonReset)

    def retranslateUi(self, Stopwatch):
        _translate = QtCore.QCoreApplication.translate
        Stopwatch.setWindowTitle(_translate("Stopwatch", "Form"))
        self.title.setText(_translate("Stopwatch", "Stopwatch"))
        self.buttonSw.setText(_translate("Stopwatch", "Start"))
        self.buttonReset.setText(_translate("Stopwatch", "Reset"))
        self.statusShow.setText(_translate("Stopwatch", "Stopwatch hasn\'t get start"))
        self.buttonShowTime.setText(_translate("Stopwatch", "Show past time"))
from qfluentwidgets import BodyLabel, PushButton, TitleLabel
